name: GS
channels:
  - defaults
  - conda-forge
dependencies:
  - _ipython_minor_entry_point=8.7.0
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=2.0.0
  - beautifulsoup4=4.11.2
  - blas=1.0
  - bleach=6.0.0
  - blosc=1.21.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - cloudpickle=2.0.0
  - colorama=0.4.6
  - comm=0.1.2
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2022.7.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - fftw=3.3.9
  - flit-core=3.8.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2022.11.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.1
  - glib=2.80.2
  - glib-tools=2.80.2
  - gst-plugins-base=1.18.5
  - gstreamer=1.20.3
  - h5py=3.7.0
  - hdf5=1.10.6
  - icc_rt=2022.1.0
  - icu=69.1
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.19.3
  - importlib-metadata=6.1.0
  - importlib_resources=5.12.0
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.7.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - jupyter_server=1.23.6
  - jupyterlab_pygments=0.2.2
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=13.0.1
  - libcurl=7.86.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libglib=2.80.2
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libllvm11=11.1.0
  - libogg=1.3.5
  - libpng=1.6.37
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - llvmlite=0.39.1
  - locket=1.0.0
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.5
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=0.5.3
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.7.3
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - notebook=6.5.3
  - notebook-shim=0.2.2
  - numba=0.56.4
  - numexpr=2.8.4
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - packaging=22.0
  - pandas=1.4.4
  - pandoc=3.2.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - pcre2=10.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyparsing=3.0.9
  - pyrsistent=0.19.3
  - python=3.10.8
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python_abi=3.10
  - pytz=2022.7.1
  - pywavelets=1.4.1
  - pywin32=306
  - pywinpty=2.0.13
  - pyyaml=6.0.1
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - scikit-learn=1.1.1
  - scipy=1.9.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - setuptools=65.5.0
  - shap=0.39.0
  - sip=6.5.1
  - six=1.16.0
  - slicer=0.0.7
  - snappy=1.1.9
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.2.0
  - tbb=2021.6.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.7.1
  - typing_extensions=4.5.0
  - tzdata=2022g
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.5.1
  - wheel=0.37.1
  - winpty=0.4.3
  - xz=5.2.8
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - alabaster==0.7.13
      - app-model==0.1.2
      - appdirs==1.4.4
      - babel==2.12.1
      - build==0.10.0
      - cachey==0.2.1
      - charset-normalizer==3.1.0
      - click==8.1.3
      - docstring-parser==0.15
      - docutils==0.17.1
      - feature-engine==1.5.2
      - freetype-py==2.3.0
      - heapdict==1.0.1
      - hsluv==5.0.3
      - imagesize==1.4.1
      - imbalanced-learn==0.10.1
      - imblearn==0.0
      - in-n-out==0.1.7
      - magicgui==0.7.2
      - markdown-it-py==2.2.0
      - matplotlib-scalebar==0.8.1
      - mdurl==0.1.2
      - mlxtend==0.22.0
      - mypy-extensions==1.0.0
      - napari==0.4.17
      - napari-console==0.0.7
      - napari-plugin-engine==0.2.0
      - napari-svg==0.1.6
      - npe2==0.6.2
      - numpy==1.25.2
      - numpydoc==1.5.0
      - patsy==0.5.3
      - pint==0.20.1
      - pooch==1.7.0
      - psygnal==0.8.1
      - pydantic==1.10.6
      - pygments==2.14.0
      - pyopengl==3.1.6
      - pyproject-hooks==1.0.0
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.11.1
      - pytomlpp==1.0.11
      - qtconsole==5.4.1
      - qtpy==2.3.0
      - requests==2.28.2
      - rich==13.3.2
      - scikit-image==0.19.3
      - snowballstemmer==2.2.0
      - sphinx==4.5.0
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - statsmodels==0.13.5
      - superqt==0.4.1
      - tomli==2.0.1
      - typer==0.7.0
      - urllib3==1.26.15
      - vispy==0.11.0
      - wrapt==1.15.0
      - xgboost==1.7.3
